### ISSUE TITLE
Güncel Liste İndirme

### ISSUE THREAD

**Issue by bertugfahriozer** [semihs/il-ilce-semt-mahalle#3]
Merhaba,

Öncelikle emeğinize sağlık güzel ve ihtiyaç karşılayan bir proje. http://postakodu.ptt.gov.tr/ siteden güncel xlsx dosyasını indirin diye not düşmüşsünüz fakat ben bir türlü erişemedim. nasıl yapacağımı benimle paylaşırsanız çok sevinirim.

**Comment by semihs** [comment]
selam, önceden sürekli güncel listenin excel indirme bağlantısını paylaşıyordu ptt fakat bu paylaşımı durdurduğunu görüyorum.
